name = "KoLesky"
uuid = "577153e7-3f34-4473-9d40-7cd00027a7f6"
authors = ["Florian Schaefer <flotosch@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
